spring:
  application:
    name: life-app
server:
  port: 8866
#eureka:
#  client:
#    service-url:
#      default-zone: http://127.0.0.1:8761/eureka/

user:
  service:
    name: user-service

book:
  service:
    name: book-service

