spring:
  application:
    name: book-service
server:
  port: 8100
eureka:
  instance:
    hostname: 192.168.0.102
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/